[package]
name = "hyprland_rs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
authors = ["AmirHossein Alesheikh <amirhossein.alesheikh@gmail.com>"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
thiserror = "1.0.37"
